Add issue templates
Unvanquished/gameplay pull request #14
Opened 2021-01-04 18:07 UTC by Gireen

2021-01-04 21:41 UTC, DolceTriade requested changes

2021-01-04 21:41 UTC, DolceTriade commented on .github/ISSUE_TEMPLATE/idea.md
> +about: Single idea without concrete problem
Suggestion

2021-01-04 21:41 UTC, DolceTriade commented on .github/ISSUE_TEMPLATE/idea-that-solves-a-problem.md
> +name: Idea that solves a problem
Enhancement

2021-01-04 23:10 UTC, Gireen commented
The intention here is to have both issues types contain idea cause there only difference is if there is a problem issue attached to them. 
So the tags make the difference and could also change one into another. Like if an related problem is not accepted as such or if a new problem can be solved by an already on its own existing idea.

2021-01-04 23:22 UTC, DolceTriade commented
I'm not sure if there is a benefit to actually separating these two categories.

2021-01-07 17:32 UTC, Viech commented
Ideas may be short and simple if they solve a problem but otherwise we don't want to track any shower thought someone's having.

2021-01-11 19:25 UTC, Gireen commented
the difference would only be the automatic set label but i think that can also be done by hand since it requires some control anyway.

2021-01-11 22:46 UTC, DolceTriade approved these changes

2021-04-11 15:22 UTC, merged